POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Test",
  "number": "012345689"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Alice",
  "number": "091234-56789"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "",
  "number": "012345689"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Test",
  "number": ""
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "xx",
  "number": "The name is too short."
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "The number is too short.",
  "number": "12345"
}